name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          yarn eslint src
          yarn prettier --check src

      - name: Compile
        run: yarn build:dev --verbose

      - name: Build project
        run: rojo build --output place.rbxlx
