name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.2.0
          run_install: true
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          pnpm eslint src
          pnpm prettier --check src

      - name: Compile
        run: pnpm build --verbose

      - name: Build project
        run: rojo build --output place.rbxlx
