name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          yarn eslint src
          yarn prettier --check src

      - name: Build & Compile
        run: yarn build --verbose
