name: Release

on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.2.0
          run_install: true
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: pnpm build --verbose

      - name: Build project
        run: rojo build --output place.rbxlx

      - name: Upload place artifact
        uses: actions/upload-artifact@v4
        with:
          name: place
          path: place.rbxlx

  deploy:
    runs-on: self-hosted
    environment: production
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@v4
        with:
          name: place

      - name: Deploy game
        run: mantle deploy --allow-purchases --environment production
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
