name: Release Canary

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - "scripts/**"
      - ".github/**"
  release:
    types: [released, prereleased]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: canary

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: yarn build --verbose

      - name: Build project
        run: rojo build --output place.rbxlx

      - name: Upload place artifact
        uses: actions/upload-artifact@v3
        with:
          name: place
          path: place.rbxlx

  deploy:
    runs-on: ubuntu-latest
    environment: canary
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@v3
        with:
          name: place
          path: ./

      - name: Deploy to Roblox
        run: rbxcloud experience publish -a "$CLOUD_DEPLOY_KEY" -u "$UNIVERSE_ID" -p "$PLACE_ID" -t published -f "place.rbxlx"
        env:
          CLOUD_DEPLOY_KEY: ${{ secrets.CLOUD_DEPLOY_KEY }}
          UNIVERSE_ID: 4902016218
          PLACE_ID: 14162328419
