name: Release

on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: yarn build --verbose

      - name: Build project
        run: rojo build --output place.rbxlx

      - name: Upload place artifact
        uses: actions/upload-artifact@v3
        with:
          name: place
          path: place.rbxlx

  deploy:
    runs-on: self-hosted
    environment: production
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@v3
        with:
          name: place
          path: ./

      - name: Deploy game
        run: mantle deploy --allow-purchases --environment production
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
